#VERSION 2.0

#HEADER
This is an example file which is designed to have more nuanced scenarios involving
comments and descriptions to see if it can trip up a KV reader. This file can be compared to "ex_base.kv", which contains the same data while ommiting this file's
traps.

Variables added here not present in base (listed as name, type):
	A (s)
	B (b)

Variables with modified descriptions: (listed as name, type, "description")
	fibonacci (m<d>) ""
	moons (m<s>) "Not all moons "
	baz (m<b>) "Nons[ense] word "

#HEADER

d pi 3.14159 //This is a // comment
d epsilon0 8.85418782e-12 ? m^-3 kg^-1 s^4 A^2 //This is a ? comment
b foo TRUE //This is a comment
s moon "Titan" //This is a comment
s mars2020 "Perserverance Rover" ? Launched 30 July 2020 //This is a comment

// Flat variables added for additional trickery
s A "This is // des//igned to be? trickier" ? Tricky! //Comment ?Fake description
b B FALSE ?Desc //Comment ?

m<d> fibonacci [0, 1, 1, 3, 5, 8] ?//Can you handle a blank description?
m<b> bar [True, False, False, True] //?This is ?a comment?//
m<s> moons ["Titan", "Europa", "Io", "Amalthea", "Callisto"] ?Not all moons //This is a comment

m<d> S_circulator [0, 0, 1 ; 1, 0, 0 ; 0, 1, 0] //This is a test
m<b> baz [false, True, false; true, False, false; true, true, FALSE] ?Nons[ense] word //This []? is a comment; ] [ m<b>
m<s> test3 ["Lorem ipsum", "dolor sit amet", "consectetur adipiscing elit."; "Ut", "nibh ipsum", "hendrerit"; "at condimentum", "in", "molestie nec mauris."] //Comment

#VERTICAL
m<d> m<s>
mass_number Nuclide
?amu ?Symbol, Name
1  "H, Hydrogen" //This ?
3  "He, Helium" //is , ;
6  "Li, Lithium" //a m<d>
12 "C, Carbon" //comment
#VERTICAL

#VERTICAL
//This
m<d> m<d>  //is m<d>
I   x  //?
1   1 //?
0   2 //a
0;	//3
0 	// Comment 4
1	//;
0;
0
0
1
// This is a comment
#VERTICAL
